name: Hello World
on: [push] # The Trigger

jobs:
  #build-app: # The Job
  running-template:
    #uses: Reusable-Templates/.github/workflows/template1.yml
    uses: MMeryy/Reusable-Templates/.github/workflows/ci.yml@main
    with:
      environment: production
      debug_mode: true
      port_number: 8080
