name: docker build
on: [push] # The Trigger

jobs:
  run-template:
     uses: MMeryy/Reusable-Templates/.github/workflows/ci.yml@main
     with: 
       environment: Production
       debug_mode: true
       port_number: 8080
           
           
        
