name: docker build
on: [push] # The Trigger
  
jobs:
  run-template: 
    uses: MMeryy/Reusable-Templates/.github/workflows/ci.yml@main
    with:
      environment: 'production'
      port_number: 8080
      debug_mode: true
    #secrets:
      #DOCKER_TOKEN: ${{ secrets.MY_PROD_TOKEN }}
