name: Hello World
on: [push] # The Trigger

jobs:
  build-app: # The Job
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Starting the build..." # The Step

      - name: Check version
        run: node -v
  run-template:
    uses: ./.github/workflows/template1.yml
    with:
      node-version: '20'
